/**
 * Analytics Agent
 * Reads metrics and generates daily KPI reports
 */

import * as path from 'path';
import {
  loadAgentConfig,
  isStopAll,
  today,
  ensureDir,
  writeFile,
  readFile,
  listFiles,
  startHealthServer,
  generateTraceId,
} from '../../shared/agent/utils.js';
import { logAgentAction, logError } from '../../shared/moltbook/ledger.js';
import { queryByDate, queryByPlatform } from '../../shared/moltbook/reader.js';

const AGENT_NAME = 'analytics';

interface DailyMetrics {
  date: string;
  summary: {
    totalEvents: number;
    successfulPosts: number;
    failedPosts: number;
    policyBlocks: number;
    platformBreakdown: Record<string, number>;
  };
  kpis: {
    postSuccessRate: number;
    avgPostsPerDay: number;
    policyComplianceRate: number;
  };
  moltbookStats: {
    totalLogs: number;
    byEventType: Record<string, number>;
    byStatus: Record<string, number>;
  };
}

/**
 * Calculate metrics from Moltbook events
 */
async function calculateMetrics(moltbookDir: string, date: string): Promise<DailyMetrics> {
  // Query events for the day
  const events = await queryByDate(moltbookDir, date);

  const summary = {
    totalEvents: events.length,
    successfulPosts: 0,
    failedPosts: 0,
    policyBlocks: 0,
    platformBreakdown: {} as Record<string, number>,
  };

  const byEventType: Record<string, number> = {};
  const byStatus: Record<string, number> = {};

  for (const event of events) {
    // Count by event type
    byEventType[event.event_type] = (byEventType[event.event_type] || 0) + 1;

    // Count by status
    byStatus[event.status] = (byStatus[event.status] || 0) + 1;

    // Platform breakdown
    if (event.platform && event.platform !== 'internal') {
      summary.platformBreakdown[event.platform] =
        (summary.platformBreakdown[event.platform] || 0) + 1;
    }

    // Count posts
    if (event.event_type === 'PLATFORM_RESULT') {
      if (event.status === 'success') {
        summary.successfulPosts++;
      } else {
        summary.failedPosts++;
      }
    }

    // Count policy blocks
    if (event.event_type === 'POLICY_DECISION' && event.status === 'blocked') {
      summary.policyBlocks++;
    }
  }

  // Calculate KPIs
  const totalPosts = summary.successfulPosts + summary.failedPosts;
  const kpis = {
    postSuccessRate: totalPosts > 0
      ? Math.round((summary.successfulPosts / totalPosts) * 100)
      : 100,
    avgPostsPerDay: summary.successfulPosts, // Single day
    policyComplianceRate: summary.policyBlocks === 0
      ? 100
      : Math.round((1 - summary.policyBlocks / Math.max(events.length, 1)) * 100),
  };

  return {
    date,
    summary,
    kpis,
    moltbookStats: {
      totalLogs: events.length,
      byEventType,
      byStatus,
    },
  };
}

/**
 * Format metrics as markdown report
 */
function formatReport(metrics: DailyMetrics): string {
  const { date, summary, kpis, moltbookStats } = metrics;

  return `# Daily Analytics Report - ${date}

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Events | ${summary.totalEvents} |
| Successful Posts | ${summary.successfulPosts} |
| Failed Posts | ${summary.failedPosts} |
| Policy Blocks | ${summary.policyBlocks} |

## KPIs

| KPI | Value | Target | Status |
|-----|-------|--------|--------|
| Post Success Rate | ${kpis.postSuccessRate}% | >90% | ${kpis.postSuccessRate >= 90 ? '✅' : '⚠️'} |
| Posts Today | ${kpis.avgPostsPerDay} | 3+ | ${kpis.avgPostsPerDay >= 3 ? '✅' : '⚠️'} |
| Policy Compliance | ${kpis.policyComplianceRate}% | 100% | ${kpis.policyComplianceRate === 100 ? '✅' : '⚠️'} |

## Platform Breakdown

| Platform | Events |
|----------|--------|
${Object.entries(summary.platformBreakdown).map(([p, c]) => `| ${p} | ${c} |`).join('\n') || '| (none) | 0 |'}

## Moltbook Statistics

### Events by Type
${Object.entries(moltbookStats.byEventType).map(([t, c]) => `- **${t}:** ${c}`).join('\n') || '- (none)'}

### Events by Status
${Object.entries(moltbookStats.byStatus).map(([s, c]) => `- **${s}:** ${c}`).join('\n') || '- (none)'}

## Recommendations

${generateRecommendations(metrics)}

---
Generated by ${AGENT_NAME} at ${new Date().toISOString()}
`;
}

/**
 * Generate recommendations based on metrics
 */
function generateRecommendations(metrics: DailyMetrics): string {
  const recommendations: string[] = [];

  if (metrics.kpis.postSuccessRate < 90) {
    recommendations.push('- ⚠️ Post success rate below target. Review failed posts and platform credentials.');
  }

  if (metrics.summary.policyBlocks > 0) {
    recommendations.push('- 🛑 Policy blocked some content. Review blocked content for compliance issues.');
  }

  if (metrics.kpis.avgPostsPerDay < 3) {
    recommendations.push('- 📈 Below target post count. Ensure content agent is generating enough drafts.');
  }

  if (Object.keys(metrics.summary.platformBreakdown).length < 2) {
    recommendations.push('- 🌐 Low platform diversity. Configure more platform credentials for broader reach.');
  }

  if (recommendations.length === 0) {
    recommendations.push('- ✅ All metrics within target. Keep up the good work!');
  }

  return recommendations.join('\n');
}

async function run(): Promise<void> {
  const config = loadAgentConfig(AGENT_NAME);
  const traceId = generateTraceId();

  console.log(`[${AGENT_NAME}] Starting...`);

  if (isStopAll(config.configDir)) {
    console.log(`[${AGENT_NAME}] STOP_ALL active, exiting`);
    process.exit(0);
  }

  try {
    const date = today();
    const analyticsDir = path.join(config.workspaceDir, 'analytics', 'daily');
    const reportPath = path.join(analyticsDir, `${date}.md`);

    ensureDir(analyticsDir);

    // Check if report already exists
    if (readFile(reportPath)) {
      console.log(`[${AGENT_NAME}] Report already exists for ${date}`);
      return;
    }

    // Calculate metrics
    const metrics = await calculateMetrics(config.moltbookDir, date);

    // Generate report
    const report = formatReport(metrics);
    writeFile(reportPath, report);

    // Also write JSON for programmatic access
    const jsonPath = path.join(analyticsDir, `${date}.json`);
    writeFile(jsonPath, JSON.stringify(metrics, null, 2));

    console.log(`[${AGENT_NAME}] Generated analytics report: ${reportPath}`);

    await logAgentAction(config.moltbookDir, {
      sourceAgent: AGENT_NAME,
      platform: 'internal',
      actionType: 'report',
      fingerprint: `analytics-${date}`,
      traceId,
      status: 'success',
      summary: `Generated analytics report for ${date}`,
      data: {
        reportPath,
        metrics: {
          totalEvents: metrics.summary.totalEvents,
          successRate: metrics.kpis.postSuccessRate,
        },
      },
    });
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    console.error(`[${AGENT_NAME}] Error:`, error);

    await logError(config.moltbookDir, {
      sourceAgent: AGENT_NAME,
      platform: 'internal',
      fingerprint: `error-${Date.now()}`,
      traceId,
      status: 'error',
      summary: `Analytics agent error: ${error}`,
      data: { error },
    });

    process.exit(1);
  }
}

// Main
const config = loadAgentConfig(AGENT_NAME);

if (config.runOnce) {
  run().then(() => process.exit(0)).catch(() => process.exit(1));
} else {
  startHealthServer(3006, AGENT_NAME);
  run();
  setInterval(run, 60 * 60 * 1000); // Run hourly
}
