/**
 * Strategy Agent
 * Generates daily briefs with content calendar and KPIs
 */

import * as path from 'path';
import {
  loadAgentConfig,
  isStopAll,
  today,
  ensureDir,
  writeFile,
  readFile,
  startHealthServer,
  generateTraceId,
} from '../../shared/agent/utils.js';
import { logAgentAction, logError } from '../../shared/moltbook/ledger.js';

const AGENT_NAME = 'strategy';

interface DailyBrief {
  date: string;
  kpis: {
    targetPosts: number;
    targetEngagement: string;
    focusTopics: string[];
  };
  contentCalendar: ContentSlot[];
  notes: string;
}

interface ContentSlot {
  time: string;
  platform: string;
  topic: string;
  type: string;
}

/**
 * Generate daily brief
 */
function generateDailyBrief(date: string): DailyBrief {
  const dayOfWeek = new Date(date).getDay();
  const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;

  // Rotate focus topics
  const allTopics = [
    'Agenium agent:// protocol',
    'Agent DNS System',
    'Domain Marketplace',
    'Agent-to-Agent communication',
    'Decentralized agent discovery',
    'Building with Agenium',
  ];

  const focusTopics = allTopics.slice(
    (dayOfWeek * 2) % allTopics.length,
    ((dayOfWeek * 2) % allTopics.length) + 2
  );

  // Content calendar based on rate limits
  const calendar: ContentSlot[] = [];

  if (!isWeekend) {
    // Weekday schedule
    calendar.push(
      { time: '09:00', platform: 'telegram', topic: focusTopics[0], type: 'announcement' },
      { time: '12:00', platform: 'x', topic: focusTopics[0], type: 'thread' },
      { time: '14:00', platform: 'discord', topic: 'community-update', type: 'embed' },
      { time: '16:00', platform: 'github', topic: focusTopics[1], type: 'discussion' },
    );
  } else {
    // Weekend: lighter schedule
    calendar.push(
      { time: '12:00', platform: 'telegram', topic: 'weekly-recap', type: 'summary' },
      { time: '15:00', platform: 'discord', topic: 'weekend-vibes', type: 'casual' },
    );
  }

  return {
    date,
    kpis: {
      targetPosts: isWeekend ? 2 : 4,
      targetEngagement: isWeekend ? '50 interactions' : '100 interactions',
      focusTopics,
    },
    contentCalendar: calendar,
    notes: isWeekend
      ? 'Weekend mode: lighter posting, focus on community engagement'
      : 'Standard weekday operations',
  };
}

/**
 * Format brief as markdown
 */
function formatBriefMarkdown(brief: DailyBrief): string {
  const lines = [
    `# Daily Brief - ${brief.date}`,
    '',
    '## KPIs',
    `- **Target Posts:** ${brief.kpis.targetPosts}`,
    `- **Target Engagement:** ${brief.kpis.targetEngagement}`,
    `- **Focus Topics:**`,
    ...brief.kpis.focusTopics.map(t => `  - ${t}`),
    '',
    '## Content Calendar',
    '',
    '| Time | Platform | Topic | Type |',
    '|------|----------|-------|------|',
    ...brief.contentCalendar.map(
      s => `| ${s.time} | ${s.platform} | ${s.topic} | ${s.type} |`
    ),
    '',
    '## Notes',
    brief.notes,
    '',
    '---',
    `Generated by ${AGENT_NAME} agent at ${new Date().toISOString()}`,
  ];

  return lines.join('\n');
}

async function run(): Promise<void> {
  const config = loadAgentConfig(AGENT_NAME);
  const traceId = generateTraceId();

  console.log(`[${AGENT_NAME}] Starting...`);

  // Check kill switch
  if (isStopAll(config.configDir)) {
    console.log(`[${AGENT_NAME}] STOP_ALL active, exiting`);
    process.exit(0);
  }

  try {
    // Generate today's brief
    const date = today();
    const brief = generateDailyBrief(date);

    // Check if brief already exists
    const briefPath = path.join(config.workspaceDir, 'briefs', `${date}.md`);
    const existingBrief = readFile(briefPath);

    if (existingBrief) {
      console.log(`[${AGENT_NAME}] Brief already exists for ${date}`);
      await logAgentAction(config.moltbookDir, {
        sourceAgent: AGENT_NAME,
        platform: 'internal',
        actionType: 'brief',
        fingerprint: `brief-${date}`,
        traceId,
        status: 'skipped',
        summary: `Brief already exists for ${date}`,
        data: { path: briefPath },
      });
      return;
    }

    // Write brief
    const markdown = formatBriefMarkdown(brief);
    ensureDir(path.dirname(briefPath));
    writeFile(briefPath, markdown);

    console.log(`[${AGENT_NAME}] Generated brief: ${briefPath}`);

    // Log to Moltbook
    await logAgentAction(config.moltbookDir, {
      sourceAgent: AGENT_NAME,
      platform: 'internal',
      actionType: 'brief',
      fingerprint: `brief-${date}`,
      traceId,
      status: 'success',
      summary: `Generated daily brief for ${date}`,
      data: {
        path: briefPath,
        kpis: brief.kpis,
        slotCount: brief.contentCalendar.length,
      },
    });
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    console.error(`[${AGENT_NAME}] Error:`, error);

    await logError(config.moltbookDir, {
      sourceAgent: AGENT_NAME,
      platform: 'internal',
      fingerprint: `error-${Date.now()}`,
      traceId,
      status: 'error',
      summary: `Strategy agent error: ${error}`,
      data: { error },
    });

    process.exit(1);
  }
}

// Main
const config = loadAgentConfig(AGENT_NAME);

if (config.runOnce) {
  run().then(() => process.exit(0)).catch(() => process.exit(1));
} else {
  // Start health server and run periodically
  startHealthServer(3001, AGENT_NAME);
  run();
  // Run daily at midnight
  setInterval(run, 24 * 60 * 60 * 1000);
}
